name: multisig-deploy-staging

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'

jobs:
  deploy-staging:
    runs-on: [self-hosted, graffino]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
        if: always()

      - name: Checkout
        id: Checkout
        uses: actions/checkout@master
        with:
          ref: 'develop'
        if: success()

      - name: Create .env
        run: |
          awk -v EXTRAS_API_TESTNET="${{ secrets.EXTRAS_API_TESTNET }}" \
              -v MAIAR_ID_API_TESTNET="${{ secrets.MAIAR_ID_API_TESTNET }}" \
              -v UNIQUE_CONTRACT_ADDRESS="${{ secrets.UNIQUE_CONTRACT_ADDRESS }}" \
              -v UNIQUE_CONTRACT_NAME="${{ secrets.UNIQUE_CONTRACT_NAME }}" \
              -v NPM_AUTH_TOKEN="${{ secrets.NPMRC }}" \
              '{ \
                  sub(/XXX_EXTRAS_API_TESTNET_XXX/, EXTRAS_API_TESTNET); \
                  sub(/XXX_MAIAR_ID_API_TESTNET_XXX/, MAIAR_ID_API_TESTNET); \
                  sub(/XXX_UNIQUE_CONTRACT_ADDRESS_XXX/, UNIQUE_CONTRACT_ADDRESS); \
                  sub(/XXX_UNIQUE_CONTRACT_NAME_XXX/, UNIQUE_CONTRACT_NAME); \
                  sub(/XXX_NPM_AUTH_TOKEN_XXX/, NPM_AUTH_TOKEN); \
                  print; \
              }' \
              .env.staging > .env

      - name: Config setup
        run: |
          make setup-testnet-wallet
          cat .npmrc

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: YARN Install
        id: YARN-Install
        if: success()
        run: yarn --network-timeout 500000

      # - name: Lint
      #   id: Lint
      #   if: success()
      #   run: |
      #     yarn lint

      - name: Build
        id: Build
        if: success()
        run: |
          export NODE_OPTIONS="--max-old-space-size=2048"
          export CI=false
          export DISABLE_ESLINT_PLUGIN=true
          yarn build

      - name: Deploy
        id: Deploy
        uses: up9cloud/action-rsync@v1.1
        if: success()
        env:
          HOST: staging.control.validblocks.com
          USER: graffino
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          SSH_ARGS: ' -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

          VERBOSE: true
          ARGS: -carEzhvP --delete-before --include '.env' --exclude '.[!.]*' --exclude vendor --exclude .docker/logs --exclude storage --exclude node_modules --exclude README* --exclude public/docs --exclude bootstrap/cache

          TARGET: ~/staging.control.validblocks.com/
          SOURCE: ./build/

          PRE_SCRIPT: |
            echo "Start at: " $(date -u)

          POST_SCRIPT: |
            echo "Stop at: " $(date -u)

      - name: DeployServer
        id: DeployServer
        uses: up9cloud/action-rsync@v1.1
        if: success()
        env:
          HOST: staging.control.validblocks.com
          USER: graffino
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          SSH_ARGS: ' -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

          VERBOSE: true
          ARGS: -carEzhvP --delete-before --include '.env' --exclude '.[!.]*' --exclude vendor --exclude .docker/logs --exclude storage --exclude node_modules --exclude README* --exclude public/docs --exclude bootstrap/cache --exclude Makefile

          TARGET: ~/staging.control.validblocks.com/server/
          SOURCE: ./server/

          PRE_SCRIPT: |
            echo "Start at: " $(date -u)

          POST_SCRIPT: |
            cd ~/staging.control.validblocks.com/server
            npm install
            echo "Stop at: " $(date -u)

      - uses: act10ns/slack@v1.2.2
        if: always()
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
